version: '3.6'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"

